### ISSUE TITLE
Mums in Technology

### ISSUE THREAD

**Issue by Nirvikalpa108** [londontechmeetups/londontechmeetups.github.io#11]
It looks like these guys [haven't met since 2017](https://www.mumsintechnology.co.uk/upcoming-events/), which is really sad as I would love to join this group! Let me know if you think we should delete them? Seems to be a shame!

**Comment by JennyBrennan** [comment]
Aw I totally agree - such an awesome group! Maybe we should keep them? As the only resource specifically for mums on the list, even if they're not meeting at the moment, maybe it's still useful to be able to find them in case people want to message them directly or read some of their resources?

**Comment by Nirvikalpa108** [comment]
Yeah I agree! I've tried to get more information from the founder, June Angelides on Twitter and LinkedIn. I've also signed up for one of her speaking events next month so fingers crossed we can get some more information on this.
Do you think for now we should put a note alerting readers that they haven't met in a while and we're still trying to get information on their status??

**Comment by JennyBrennan** [comment]
That sounds like a great idea - thank you for digging into this!
