### ISSUE TITLE
Founders & Coders

### ISSUE THREAD

**Issue by Nirvikalpa108** [londontechmeetups/londontechmeetups.github.io#8]
Hi @JennyBrennan, I've submitted a PR for the beginner-friendly meetup section, which includes a change to the Founders & Coders link. 

They no longer seem to run a Coding for Everyone meetup as far as I can see. It seems they are just running a Coding for Women event (which includes all underrepresented groups I understand). 

I've only just seen that you already had Coding for Women in the underrepresented groups section which follows! Where would you like to put it? In the Beginners or Underrepresented Groups section?

Thanks! 😃

**Comment by JennyBrennan** [comment]
Thanks so much for your PRs - these are awesome! I think it'd be best in the underrepresented groups section to be most consistent. I've generally been putting all meetups specifically for people of underrepresented groups in that section, and not the other sections, to try and make it quicker for people to find them. Thank you again!

**Comment by Nirvikalpa108** [comment]
Great, I totally agree! 😃 Best to put the meetups for u/r groups in that section and not the others to make the site more user friendly!
